config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('lock/web/__admin__/', admin.site.urls),
    # path('', include('journal.urls', namespace='journal')),
    # path('', include('users.urls', namespace='users')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('journal.urls', namespace='journal')),
    path('', include('users.urls', namespace='users')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'




urlpatterns = [
    path('', views.main_page, name='main_page'),

    path('contact/', views.contact, name='contact'),
    path('save_contact/', views.save_contact, name='save_contact'),

    path('editorial/list/', views.editorial_list, name='editorial_list'),
    path('editorial/<int:id>/', views.editorial_detail, name='editorial_detail'),
    path('editorial/update/<int:id>/', views.editorial_update, name='editorial_update'),
    path('editorial/delete/<int:id>/', views.editorial_delete,
         name='editorial_delete'),
    path('editorial/create/', views.editorial_create.as_view(), name='editorial_create'),


    path('article/list/', views.article_list, name='article_list'),
    path('article/<slug:slug>/<int:id>/',
         views.article_detail, name='article_detail'),
    path('article/update/<slug:slug>/<int:id>/',
         views.article_update, name='article_update'),
    path('article/delete/<slug:slug>/<int:id>/', views.article_delete,
         name='article_delete'),
    path('article/create/', views.article_create, name='article_create'),

    path('post/list/',
         views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/<int:id>/',
         views.PostDetailView, name='post_detail'),
    path('post/update/<slug:slug>/<int:id>/',
         views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/<int:id>/',
         views.PostDeleteView, name='post_delete'),
    path('post/create/', views.PostCreateView.as_view(),
         name='post_create'),

    path('journal/list/', views.journal_list, name='journal_list'),
    path('journal/create/', views.journal_create, name='journal_create'),
    path('journal/update/<int:id>/', views.journal_update, name='journal_update'),
    path('journal/delete/<int:id>/', views.journal_delete, name='journal_delete'),

    path('social/list/', views.social_media_list, name='social_media_list'),
    path('social/update/<int:id>/', views.social_media_update, name='social_media_update'),
    path('social/delete/<int:id>/', views.social_media_delete, name='social_media_delete'),
    path('social/create/', views.social_media_create, name='social_media_create'),

    path('message/list/', views.message_list, name='message_list'),
    path('message/delete/all/', views.message_delete_all, name='message_delete_all'),

    path('journal/about/', views.about, name='about_journal'),
    path('journal/about/<int:id>/', views.about_article_update, name='about_article_update'),
    path('booking/article/', views.booking_article, name='booking_article'),
    path('booking/article/<int:id>/', views.sending_article_update, name='sending_article_update'),

]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


app_name = 'users'


urlpatterns = [

    #
    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # path("", include('django.contrib.auth.urls')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update')


]

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from utils.models import BaseModel

User = get_user_model()


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='profile')
    photo = models.ImageField(upload_to='images/profile/%Y/%m/%d',
                              blank=True, null=True)
    date_birth = models.DateField(blank=True, null=True)
    telephone = models.CharField(max_length=13, blank=True, null=True)
    is_admin = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return f'Profile for User(id={self.user_id})'


class Statistic(BaseModel):
    profile = models.ForeignKey(Profile, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='visits')
    day = models.DateTimeField(auto_now_add=True)
    number = models.IntegerField(default=0)

    objects = models.Manager()

users/forms.py
from django import forms
from .models import Profile, User


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password'
    }))


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'form-control my-2'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control my-2',
        'placeholder': 'Password confirm'}))

    class Meta:
        fields = (
            'username',
            'email',
            'first_name',
            'last_name'
        )
        model = User

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'example@gmail.com'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'First name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'Last name'
            })
        }

    def clean_password2(self):
        password2 = self.cleaned_data.get("password2")
        if password2 != self.cleaned_data["password"]:
            raise forms.ValidationError("Password not match!")

        return password2

    def clean_email(self):

        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Bunday e-mailli faydalanuvchi mavjud!")

        return email


class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'telephone',
            'photo',
            'date_birth',
        )
        widgets = {
            'telephone': forms.TextInput(attrs={
                'class': 'form-control my-2',
                'placeholder': '+998998765432'
            }),

            'photo': forms.FileInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'Photo for profile'
            }),
            'date_birth': forms.DateInput(attrs={
                'class': 'form-control my-2', 'placeholder': "yil-oy-kun | 2000-01-01",
                'type': 'date'
            }),
        }

    def clean_telephone(self):

        telephone = self.cleaned_data['telephone']
        if telephone:
            if len(telephone) == 13 and telephone.startswith("+998"):
                numbers: str = telephone[3:]
                if numbers.isdigit():
                    return telephone
            else:
                raise forms.ValidationError('Invalid telephone number')
        return telephone


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'example@gmail.com'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'First name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control my-2',
                'placeholder': 'Last name'
            })
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError("Bunday e-mailli faydalanuvchi mavjud!")

        return email

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, logout
# from journal.functions import get_or_save_statistic

from .forms import UserCreateForm, ProfileCreateForm, LoginForm, UserUpdateForm


User = get_user_model()


def register(request: HttpRequest):
    # get_or_save_statistic(request)
    if request.method == 'POST':
        user_form = UserCreateForm(data=request.POST)
        profile_form = ProfileCreateForm(data=request.POST,
                                         files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(
                user_form.cleaned_data['password']
            )
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, "Siz ro'yxatdan mavaffaqiyatli o'tdingiz! ✅")
            return redirect('users:login')
        else:
            messages.warning(request, "Ro'yxatdan o'tmadiz, ya'na harakat qilib ko'ring! ⚠️")
    else:
        user_form = UserCreateForm()
        profile_form = ProfileCreateForm()

    return render(request, 'users/signup.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


def user_login(request: HttpRequest):
#     get_or_save_statistic(request)
    if request.method == 'POST':
        user_form = LoginForm(data=request.POST)
        if user_form.is_valid():
            cd = user_form.cleaned_data

            user = authenticate(
                username=cd['username'],
                password=cd['password']
            )
            if user:
                if user.is_active:
                    login(request, user)
                    messages.success(request, "Siz tizimga muvaffaqityatli kirdingiz! ✅")
                    return redirect('journal:main_page')
                else:
                    messages.warning(request, "Foydalanuvchi faol emas! ⚠️")
                    return redirect('users:login')
            else:
                messages.error(request, "Bunday foydalanuvchi mavjud emas! ❌",
                               extra_tags="danger")
                return redirect('users:login')
    else:
        user_form = LoginForm()

    return render(request, 'registration/login.html',
                  {'form': user_form})


@login_required
def profile(request: HttpRequest):
#     get_or_save_statistic(request)
    return render(request, 'users/_profile.html',
                  {'user': request.user,
                   'profile': request.profile})


@login_required
def user_logout(request: HttpRequest):
    logout(request)
    messages.info(request, "Siz tizimdan chiqdingiz ❗️❗️")
    return redirect('users:login')


@login_required
def profile_update(request: HttpRequest):
#     get_or_save_statistic(request)
    user = request.user
    profile = request.profile

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = ProfileCreateForm(data=request.POST, instance=profile,
                                         files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, "Profil muvaffaqiyatli o'zgartirildi!")
            return redirect('users:profile')
        else:
            messages.error(request, "Iltimos, to'g'ri ma'lumotlar kiriting!")
    else:
        user_form = UserUpdateForm(instance=user)
        profile_form = ProfileCreateForm(instance=profile)

    return render(request,
                  'users/profile_update.html',
                  context={
                      'user_form': user_form,
                      'profile_form': profile_form
                  })

users/templates/users/components/.admin.html
{% load static %}
{% load i18n %}
{% load journal_tags %}

<li class="fornow">
    <a href="{% url 'journal:article_create' %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">Maqola yozish</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">Write an article</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">Написать статью</span>
        {% endif %}
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:post_create' %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">
                        {% blocktrans %}Yangilik qo'shish{% endblocktrans %}
                    </span>
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:journal_create' %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Jurnal qo'shish{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Add an journal{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Добавить журнал{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:editorial_create' %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Tahrirlovchi qo'shish{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Add editor{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Добавить редактор{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:about_article_update' id=1 %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Jurnal haqidani o'zgartirish{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Change the about journal{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Изменения в журнале{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:sending_article_update' id=1 %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Ma'qola yuborishni o'zgartirish{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Change article submission{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Изменить отправку статьи{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:social_media_create' %}" class="nav-link" style="color: blue;">
        <i class="fa-regular text-warning fa-plus fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Ijtimoiy tarmoq qo'shish{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Add social network{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Добавить социальную сеть{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="fornow">
    <a href="{% url 'journal:social_media_list' %}" class="nav-link" style="color: blue;">
        <i class="fa-solid text-warning fa-hashtag fs-3"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Ijtimoiy tarmoqlar{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Social networks{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">{% blocktrans %}Социальные сети{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
{% get_messages_count as count %}
<li class="fornow">
    <a href="{% url 'journal:message_list' %}" class="nav-link" style="color: blue;">
        <i class="fa-solid text-warning fa-comment-sms fs-3"></i>
        <span class="span-hover-in-user span-color-in-user" style="font-size: larger">
                        {% blocktrans %}Xabarlar{% endblocktrans %}
            {% if count != 0 %}
            <span class="badge text-bg-primary rounded-pill ms-4">
                    {{ count }}
            </span>
            {% endif %}
                    </span>

    </a>
</li>

users/templates/users/components/.common.html
{% load static %}
{% load i18n %}
<li class="nav-item fornow">
    <a class="nav-link active" href="{% url 'users:profile_update' %}">
        <i class="lime-color fa-regular fa-pen-to-square fs-4" style="color: red"></i>
        <span class="span-color-always2" style="color: red">{% blocktrans %}Profile tahrirlash{% endblocktrans %}</span>
    </a>
</li>
<li class="nav-item fornow">
    <a class="nav-link active" href="{% url 'password_change' %}">
        <i class="lime-color fa-solid fa-key fs-4" style="color: red"></i>
        <span class="span-color-always2" style="color: red">{% blocktrans %}Parolni almashtirish{% endblocktrans %}</span>
    </a>
</li>
<li class="nav-item fornow">
    <a class="nav-link active" href="{% url 'users:logout' %}">
        <i class="lime-color fa-solid fa-right-from-bracket fs-4" style="color: red"></i>
        <span class="span-color-always2" style="color: red">{% blocktrans %}Chiqish{% endblocktrans %}</span>
    </a>
</li>

users/templates/users/components/.navbar.html
{% load static %}
{% load i18n %}
<li class="nav-item hover-panel">
    <a class="nav-link active" href="{% url 'journal:main_page' %}">
        <i style="color: red" class="fa-solid fa-house fs-4"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-color-always">{% blocktrans %}Asosiy{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-color-always">{% blocktrans %}Main{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-color-always">{% blocktrans %}Основной{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:post_list' %}">
        <i class="fa-regular fa-newspaper fs-4" style="color: red"></i>
        <span class="span-color-always">{% blocktrans %}Yangiliklar{% endblocktrans %}</span>
    </a>
</li>
<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:article_list' %}">
        <i style="color: red" class="fa-solid fa-book-journal-whills fs-4"></i>
        <span class="span-color-always">{% blocktrans %}Maqolalar{% endblocktrans %}</span>
    </a>
</li>
<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:contact' %}">
        <i style="color: red" class=" fa-regular fa-address-book fs-4"></i>
        <span class="span-color-always">{% blocktrans %}Bog'lanish{% endblocktrans %}</span>
    </a>
</li>
<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:journal_list' %}">
        <i style="color: red" class=" fa-regular fa-folder-open fs-4"></i>
        <span class="span-color-always">{% blocktrans %}Arxiv{% endblocktrans %}</span>
    </a>
</li>
<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:booking_article' %}">
        <i style="color: red" class=" fa-regular fa-pen-to-square fs-4"></i>
        {% get_current_language as LANGUAGE_CODE %}
        {% if LANGUAGE_CODE == "uz" %}
        <span class="span-color-always">{% blocktrans %}Maqola yuborish{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "en" %}
        <span class="span-color-always">{% blocktrans %}Sending article{% endblocktrans %}</span>
        {% elif LANGUAGE_CODE == "ru" %}
        <span class="span-color-always">{% blocktrans %}Отправка статьи{% endblocktrans %}</span>
        {% endif %}
    </a>
</li>
<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:about_journal' %}">
        <i style="color: red" class=" fa-solid fa-circle-info fs-4"></i>
        <span class="span-color-always">{% blocktrans %}Jurnal haqida{% endblocktrans %}</span>
    </a>
</li>

<li class="nav-item hover-panel">
    <a class="nav-link active" aria-current="page" href="{% url 'journal:editorial_list' %}">
        <i class="fa-solid fa-people-group fs-5" style="color: red"></i>
        <span class="span-color-always">{% blocktrans %}Tahririyat{% endblocktrans %}</span>
    </a>
</li>