config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('lock/web/__admin__/', admin.site.urls),
    # path('', include('journal.urls', namespace='journal')),
    # path('', include('users.urls', namespace='users')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('journal.urls', namespace='journal')),
    path('', include('users.urls', namespace='users')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'




urlpatterns = [
    path('', views.main_page, name='main_page'),

    path('contact/', views.contact, name='contact'),
    path('save_contact/', views.save_contact, name='save_contact'),

    path('editorial/list/', views.editorial_list, name='editorial_list'),
    path('editorial/<int:id>/', views.editorial_detail, name='editorial_detail'),
    path('editorial/update/<int:id>/', views.editorial_update, name='editorial_update'),
    path('editorial/delete/<int:id>/', views.editorial_delete,
         name='editorial_delete'),
    path('editorial/create/', views.editorial_create.as_view(), name='editorial_create'),


    path('article/list/', views.article_list, name='article_list'),
    path('article/<slug:slug>/<int:id>/',
         views.article_detail, name='article_detail'),
    path('article/update/<slug:slug>/<int:id>/',
         views.article_update, name='article_update'),
    path('article/delete/<slug:slug>/<int:id>/', views.article_delete,
         name='article_delete'),
    path('article/create/', views.article_create, name='article_create'),

    path('post/list/',
         views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/<int:id>/',
         views.PostDetailView, name='post_detail'),
    path('post/update/<slug:slug>/<int:id>/',
         views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/<int:id>/',
         views.PostDeleteView, name='post_delete'),
    path('post/create/', views.PostCreateView.as_view(),
         name='post_create'),

    path('journal/list/', views.journal_list, name='journal_list'),
    path('journal/create/', views.journal_create, name='journal_create'),
    path('journal/update/<int:id>/', views.journal_update, name='journal_update'),
    path('journal/delete/<int:id>/', views.journal_delete, name='journal_delete'),

    path('social/list/', views.social_media_list, name='social_media_list'),
    path('social/update/<int:id>/', views.social_media_update, name='social_media_update'),
    path('social/delete/<int:id>/', views.social_media_delete, name='social_media_delete'),
    path('social/create/', views.social_media_create, name='social_media_create'),

    path('message/list/', views.message_list, name='message_list'),
    path('message/delete/all/', views.message_delete_all, name='message_delete_all'),

    path('journal/about/', views.about, name='about_journal'),
    path('journal/about/<int:id>/', views.about_article_update, name='about_article_update'),
    path('booking/article/', views.booking_article, name='booking_article'),
    path('booking/article/<int:id>/', views.sending_article_update, name='sending_article_update'),

]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


app_name = 'users'


urlpatterns = [

    #
    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # path("", include('django.contrib.auth.urls')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update')


]

journal/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.http import Http404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


from django.http import HttpRequest, HttpResponseForbidden, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import Journal, Post, Article, SocialMedia, About, Contact, SendingArticle, Editorial
from .forms import ContactForm, ArticleForm, PostForm, JournalForm, SocialForm, AboutForm, SendingArticleForm, \
    EditorialForm
# from journal.functions import get_or_save_statistic


def main_page(request: HttpRequest):
    # get_or_save_statistic(request)
    posts = Post.objects.all()[:2]
    articles = Article.objects.all()[:3]

    context = {
        'posts': posts,
        'articles': articles
    }

    return render(request,
                  'journal/home.html',
                  context=context)


def journal_list(request: HttpRequest):
#     get_or_save_statistic(request)
    journals = Journal.objects.all()
    return render(request,
                  template_name='journal/journal/list.html',
                  context={
                      'journals': journals
                  })


@login_required
def journal_create(request: HttpRequest):

    if not request.profile.is_admin:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = JournalForm(data=request.POST,
                           files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('journal:journal_list')
    else:
        form = JournalForm()

    return render(request, 'journal/journal/create.html',
                  {'form': form})


@login_required
def journal_update(request: HttpRequest, id):
    if not request.profile.is_admin:
        return HttpResponseForbidden()

    journal = get_object_or_404(Journal,
                                id=id)

    if request.method == 'POST':
        form = JournalForm(data=request.POST, instance=journal,
                           files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('journal:journal_list')
    else:
        form = JournalForm(instance=journal)

    return render(request, 'journal/journal/update.html',
                  {
                      'form': form,
                      'journal': journal
                  })


@login_required
def journal_delete(request: HttpRequest, id):
    if not request.profile.is_admin:
        return HttpResponseForbidden()

    journal = get_object_or_404(Journal,
                                id=id)

    if request.method == 'POST':
        journal.delete()
        return redirect('journal:journal_list')

    return render(request, 'journal/journal/delete.html',
                  {'journal': journal})


@login_required
def contact(request: HttpRequest):
#     get_or_save_statistic(request)
    form = ContactForm()

    context = {
        'form': form
    }

    return render(request, 'journal/contact.html',
                  context=context)


@login_required
@require_POST
def save_contact(request: HttpRequest):
    form = ContactForm(data=request.POST)
    if form.is_valid():

        contact = form.save(commit=False)
        contact.sender = request.user
        contact.save()
        messages.success(request, 'Sizning xabaringiz muvaffaqiyatli yuborildi!  ✅')

    else:
        messages.error(request, 'Iltimos to\'g\'ri ma\'lumot kiriting! ❌', extra_tags='danger')

    return redirect('journal:contact')


@login_required
def message_list(request: HttpRequest):

    messages = Contact.objects.all().order_by('-created_at').select_related('sender', 'sender__profile')
    messages.update(is_read=True)
    messages_count = messages.count()
    paginator = Paginator(messages, 5)
    page_number = request.GET.get('page', 1)

    try:
        messages = paginator.page(page_number)
    except PageNotAnInteger:
        messages = paginator.page(1)
    except EmptyPage:
        messages = paginator.page(paginator.num_pages)

    return render(request, 'journal/message/list.html',
                  {
                      'messages': messages,
                      'messages_count': messages_count
                  })


@require_POST
def message_delete_all(request: HttpRequest):
    if not request.user.profile.is_admin:
        return HttpResponseForbidden()
    messages = Contact.objects.filter(is_read=True)
    messages.delete()
    return redirect('users:profile')


def about(request: HttpRequest):
    datas = About.objects.all().first()

    return render(request, context={'datas': datas},
                  template_name='journal/about/about.html')


def booking_article(request: HttpRequest):
    data = SendingArticle.objects.all().first()
    context = {"data": data}
    return render(request, 'journal/guide_for_authors.html', context)


def editorial_list(request: HttpRequest):
    editorials = Editorial.objects.all()
    paginator = Paginator(editorials, 14)
    page_number = request.GET.get('page', 1)

    try:
        editorials = paginator.page(page_number)
    except PageNotAnInteger:
        editorials = paginator.page(1)
    except EmptyPage:
        editorials = paginator.page(paginator.num_pages)

    return render(request, context={
        'editorials': editorials,
        'pag_start':False,
        'pag_end':False,
    }, template_name='journal/editorial/list.html')


def article_list(request: HttpRequest):
    articles = Article.objects.all()
    paginator = Paginator(articles, 5)
    page_number = request.GET.get('page', 1)

    try:
        articles = paginator.page(page_number)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)


    return render(request,
                  'journal/article/list.html',
                  context={
                      'articles': articles,
                      'pag_start': False,
                      'pag_end': False,
                  })

def editorial_detail(request: HttpRequest, id):
    editorial = get_object_or_404(Editorial, id=id)
    return render(request, context={'editorial': editorial}, template_name='journal/editorial/detail.html')


def article_detail(request: HttpRequest, slug, id):
#     get_or_save_statistic(request)
    article = get_object_or_404(Article,
                                slug=slug,
                                id=id)
    article.views += 1
    article.save()

    return render(request, 'journal/article/detail.html',
                  {'article': article})


@login_required
def article_create(request: HttpRequest):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = ArticleForm(data=request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            if not article.slug:
                article.slug = slugify(article.title)
                article.save()

            return redirect('journal:article_detail',
                            slug=article.slug,
                            id=article.id)
    else:
        form = ArticleForm()

    context = {
        'form': form
    }

    return render(request,
                  'journal/article/create.html',
                  context=context)

# @login_required
# def editorial_create(request: HttpRequest):
#     if not request.user.is_superuser:
#         return HttpResponseForbidden()
#
#     if request.method == 'POST':
#         form = EditorialForm(data=request.POST)
#         if form.is_valid():
#             editorial = form.save()
#             return redirect('journal:editorial_detail', id=editorial.id)
#     else:
#         form = EditorialForm()
#
#     return render(request, 'journal/editorial/create.html',{'form': form})
class editorial_create(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'journal/editorial/create.html'
    model = Editorial
    form_class = EditorialForm

    def get_success_url(self):
        return reverse_lazy('journal:editorial_detail', kwargs={'id': self.object.pk})

    # def form_valid(self, form):
    #     instance = form.save(commit=False)
    #     instance.author = self.request.user
    #     instance.save()
    #     return super().form_valid(form)

    def test_func(self):
        return self.request.profile.is_admin



@login_required
def article_update(request: HttpRequest, slug, id):
    article = get_object_or_404(Article,
                                slug=slug, id=id)

    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = ArticleForm(data=request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('journal:article_detail',
                            slug=article.slug,
                            id=article.id)
    else:
        form = ArticleForm(instance=article)

    return render(request, 'journal/article/update.html',
                  {'form': form,
                   'article': article})


@login_required
def editorial_update(request: HttpRequest, id):
    editorial = get_object_or_404(Editorial, id=id)

    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = EditorialForm(data=request.POST, instance=editorial)
        if form.is_valid():
            editorial = form.save()
            return redirect('journal:editorial_detail', id = editorial.id)
    else:
        form = EditorialForm(instance=editorial)

journal/templates/journal/message/delete.html
{% extends 'users/profile.html' %}
{% load static %}
{% load i18n %}
{% block title %}
{% blocktrans %}Xabarlar{% endblocktrans %}
{% endblock title %}


{% block content %}
<div class="container font-consolas">
    <p class="text-uppercase ms-5 fw-bold fs-4 font-consolas">{% blocktrans %}Xabarlar ro'yxati{% endblocktrans %} (<span class="fs-5 text-info">{{ messages_count }}</span>) </p>
    {% for message in messages %}
    <div class="card col-8 shadow border-0 mb-3">
        <div class="card-header fw-bold ">
            <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                <li class="text-danger">
                    <a class="nav-link">
                       <i class="text-secondary fa-solid fa-user fs-4">: </i>
                        <span style="font-size: larger" class="text-info">
                            {{ message.sender.username }}
                        </span>
                    </a>
                </li>
                <li class="">
                    <a class="nav-link">
                        <i class="text-secondary fa-solid fa-phone  fs-4">: </i>
                        <span style="font-size: larger" class="text-info">{{ message.sender.profile.telephone }}</span>
                    </a>
                </li>
                <li class="">
                    <a class="nav-link">
                        <i class="text-secondary fa-solid fa-envelope fs-4">: </i>
                        <span style="font-size: larger" class="text-info">{{ message.sender.email }}</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="card-body  bg-info">
            <h5 class="card-title text-center alert alert-info">{{ message.sender.username|title }}{% blocktrans %}dan kelgan xabar{% endblocktrans %}</h5>
            <hr class="my-2 text-secondary ">
            <p class="card-text text-dark fw-bolder fs-6">{{ message.message }}</p>
        </div>
        <div class="card-footer text-body-secondary">
            {{ message.created_at|timesince }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

journal/templates/journal/message/list.html
{% extends 'users/_profile.html' %}
{% load static %}
{% load i18n %}
{% block title %}
{% blocktrans %}Xabarlar{% endblocktrans %}
{% endblock title %}

<div class="mt-4 pt-4 col"></div>
{% block content %}
<div class="container font-consolas pt-4 mt-4">
    <div class="text-center text-uppercase fw-bold fs4 font-consolas mb-2">
        {% blocktrans %}Xabarlar ro'yxati {% endblocktrans %}(<span class="fs-xxl-5 text-info">{{ messages_count }}</span>)
        {% if messages_count > 0 %}
            <form action="{% url 'journal:message_delete_all' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">{% blocktrans %}Barcha xabarlarni o'chirish{% endblocktrans %}</button>
            </form>
        {% endif %}
    </div>

    {% for message in messages %}
    <div class="card col-xxl-8 shadow border-0 mb-3">
        <div class="card-header fw-bold ">
            <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                <li class="text-danger">
                    <a class="nav-link">
                        <i class="text-secondary fa-solid fa-user fs-4">: </i>
                        <span class="fs-6 text-info">
                            {{ message.sender.username }}
                        </span>
                    </a>
                </li>
                <li class="">
                    <a class="nav-link">
                        <i class="text-secondary fa-solid fa-phone  fs-4">: </i>
                        <span class="fs-6 text-info">{{ message.sender.profile.telephone }}</span>
                    </a>
                </li>
                <li class="">
                    <a class="nav-link">
                        <i class="text-secondary fa-solid fa-envelope fs-4">: </i>
                        <span class="fs-6 text-info">{{ message.sender.email }}</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="card-body  bg-info">
            <h5 class="card-title text-center alert alert-info">{{ message.sender.username|title }}{% blocktrans %}dan kelgan xabar{% endblocktrans %}</h5>
            <hr class="my-2 text-secondary ">
            <p class="card-text text-dark fw-bolder fs-6">{{ message.message }}</p>
        </div>
        <div class="card-footer text-body-secondary">
            {{ message.created_at|timesince }}
        </div>
    </div>
    {% endfor %}
    {% include 'journal/includes/pagination.html' with page=messages %}
</div>
{% endblock content %}


from journal.models import Contact
from django.contrib.auth import get_user_model
User = get_user_model()
user1 = User.objects.get(pk=4)