config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('lock/web/__admin__/', admin.site.urls),
    # path('', include('journal.urls', namespace='journal')),
    # path('', include('users.urls', namespace='users')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('journal.urls', namespace='journal')),
    path('', include('users.urls', namespace='users')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'




urlpatterns = [
    path('', views.main_page, name='main_page'),

    path('contact/', views.contact, name='contact'),
    path('save_contact/', views.save_contact, name='save_contact'),

    path('editorial/list/', views.editorial_list, name='editorial_list'),
    path('editorial/<int:id>/', views.editorial_detail, name='editorial_detail'),
    path('editorial/update/<int:id>/', views.editorial_update, name='editorial_update'),
    path('editorial/delete/<int:id>/', views.editorial_delete,
         name='editorial_delete'),
    path('editorial/create/', views.editorial_create.as_view(), name='editorial_create'),


    path('article/list/', views.article_list, name='article_list'),
    path('article/<slug:slug>/<int:id>/',
         views.article_detail, name='article_detail'),
    path('article/update/<slug:slug>/<int:id>/',
         views.article_update, name='article_update'),
    path('article/delete/<slug:slug>/<int:id>/', views.article_delete,
         name='article_delete'),
    path('article/create/', views.article_create, name='article_create'),

    path('post/list/',
         views.PostListView.as_view(), name='post_list'),
    path('post/<slug:slug>/<int:id>/',
         views.PostDetailView, name='post_detail'),
    path('post/update/<slug:slug>/<int:id>/',
         views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<slug:slug>/<int:id>/',
         views.PostDeleteView, name='post_delete'),
    path('post/create/', views.PostCreateView.as_view(),
         name='post_create'),

    path('journal/list/', views.journal_list, name='journal_list'),
    path('journal/create/', views.journal_create, name='journal_create'),
    path('journal/update/<int:id>/', views.journal_update, name='journal_update'),
    path('journal/delete/<int:id>/', views.journal_delete, name='journal_delete'),

    path('social/list/', views.social_media_list, name='social_media_list'),
    path('social/update/<int:id>/', views.social_media_update, name='social_media_update'),
    path('social/delete/<int:id>/', views.social_media_delete, name='social_media_delete'),
    path('social/create/', views.social_media_create, name='social_media_create'),

    path('message/list/', views.message_list, name='message_list'),
    path('message/delete/all/', views.message_delete_all, name='message_delete_all'),

    path('journal/about/', views.about, name='about_journal'),
    path('journal/about/<int:id>/', views.about_article_update, name='about_article_update'),
    path('booking/article/', views.booking_article, name='booking_article'),
    path('booking/article/<int:id>/', views.sending_article_update, name='sending_article_update'),

]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


app_name = 'users'


urlpatterns = [

    #
    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # path("", include('django.contrib.auth.urls')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update')


]

templates/components/._header.html
{% load static %}
{% load i18n %}

<div class="container-fluid">
    <div class="row">
        <nav class="navbar navbar-expand-lg" style="background-color: #8eecf5; margin-top: 8px">
            <div class="col-sm-1"></div>
            <div class="container-fluid">
                {% get_current_language as LANGUAGE_CODE %}
                {% if LANGUAGE_CODE == "en" %}
                <a class="navbar-brand fw-bold fs-3 fornow" style="" href="{% url 'journal:main_page' %}">
                    {% blocktrans %} Surkhandarya: Science and mind {% endblocktrans %}
                </a>
                {% elif LANGUAGE_CODE == "uz" %}
                <a class="navbar-brand fw-bold fs-3 fornow" style="" href="{% url 'journal:main_page' %}">
                    {% blocktrans %} Surxondaryo: Ilm va tafakkur {% endblocktrans %}
                </a>
                {% elif LANGUAGE_CODE == "ru" %}
                <a class="navbar-brand fw-bold fs-3 fornow" style="" href="{% url 'journal:main_page' %}">
                    {% blocktrans %} Сурхандаря: наука и мнение {% endblocktrans %}
                </a>
                {% endif %}
                <div class="col-lg offset-lg-2">
                    <img style="width: 5rem;" src="{% static 'images/book.png' %}"
                         alt="book">
                </div>
                <button class="navbar-toggler bg-lime" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <form id="language-form" action="{% url 'set_language' %}" method="post" class="borderim">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select id="language-select" name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                        {% endfor %}
                    </select>
                    <noscript><input type="submit" value="Go"></noscript>
                </form>
                <nav class="navbar navbar-expand-sm" style="background-color: #8eecf5">


                    <div class="container-fluid malak">
                        <div class="row">
                            <div class="col-lg-12 col-lg my-2 d-flex justify-content-end  ">
                                {% if not request.user.is_authenticated %}
                                <a href="{% url 'users:login' %}" class="btn btn-outline-dark me-2">
                                    {% blocktrans %}Kirish{% endblocktrans %}
                                </a>
                                <a href="{% url 'users:register' %}" class="btn btn-outline-danger">
                                    {% blocktrans %}Ro'yxatdan o'tish{% endblocktrans %}
                                </a>
                                {% else %}
                                {% include 'components/.profile.html' %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </nav>

            </div>


        </nav>

        <nav class="navbar navbar-expand-lg" style="background-color: #8eecf5">
            <div class="col-sm-1"></div>
            <div class="container-fluid">


                <div class="row">
                    <div class="collapse navbar-collapse ms-0 malak" id="navbarSupportedContent">

                        <ul class="navbar-nav me-0 mb-2 mb-lg-0">
                            {% include 'users/components/.navbar.html' %}
                        </ul>
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        </ul>

                    </div>
                </div>


            </div>

        </nav>
    </div>
</div>


<script>
    document.getElementById('language-select').onchange = function() {
        document.getElementById('language-form').submit();
    };
</script>

templates/components/.footer.html
{% load static %}
{% load journal_tags %}
{% load i18n %}
<div class="" style="height: 10rem;"></div>
<div class="container mb-4">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center flex-row">
            <div class="p-2">
                <a class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                    <i class="fa-brands fa-python fs-2" style="color: #00FF7F;"></i>
                </a>
                <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Company, Inc</span>
            </div>
            <div class="p-2">
                <div class="d-inline me-2">
                    <a href="https://t.me/jamshidchoriyevDev" style="text-decoration: none;">
                        <img class="text-start" style="width: 2rem;" src="{% static 'images/free-icon-dev.png' %}"
                             alt="Jamshid">
                    </a>
                </div>
                <div class="d-inline ms-2">
                    <a href="https://t.me/mcJahongir">
                        <img class="text-start" style="width: 2rem;" src="{% static 'images/free-icon-developer.png' %}"
                             alt="Jahongir">
                    </a>
                </div>
            </div>
    </footer>
</div>
<div class="container">
    <ul class="nav col-md-12 justify-content-end list-unstyled d-flex">
        {% get_social_media as social_media %}

        {% for social in social_media %}
        <li class="ms-3">
            <a class="text-body-secondary fs-3" href="{{ social.url }}">
                <i class="fa-brands {% if social.title == 'instagram' %} fa-square-{{ social.title }} {% else %} fa-{{ social.title }} {% endif %}"
                   style="color: {{ social.color }};"></i>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>


</div>
<div class="" style="height: 3rem;"></div>

templates/components/.header.html
{% load static %}
{% load i18n %}
<div class="px-3 py-2 text-bg-dark border-bottom">
    <div class="mx-5">
        <div class="container-fluid d-flex flex-wrap align-items-center justify-content-right justify-content-lg-start">
            <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                <span class="font-ink-free fs-2 ">{% blocktrans %}Surxondaryo: ilm va tafakkur{% endblocktrans %}</span>
            </a>

            <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                <li class="hover-panel">
                    <a href="{% url 'journal:main_page' %}" class="nav-link" style="color: lime;">
                        <i class="fa-solid fa-house fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Asosiy{% endblocktrans %}</span>
                    </a>
                </li>
                <li class="hover-panel">
                    <a href="{% url 'journal:post_list' %}" class="nav-link" style="color: lime;">
                        <i class="fa-regular fa-newspaper fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Yangiliklar{% endblocktrans %}</span>
                    </a>
                </li>
                <li class="hover-panel">
                    <a href="{% url 'journal:article_list' %}" class="nav-link" style="color: lime;">
                        <i class="fa-solid fa-book-journal-whills fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Maqolalar{% endblocktrans %}</span>
                    </a>
                </li>
                <li class="hover-panel">
                    <a href="{% url 'journal:contact' %}" class="nav-link" style="color: lime;">
                        <i class="fa-regular fa-address-book fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Bog'lanish{% endblocktrans %}</span>
                    </a>
                </li>
                 <li class="hover-panel">
                    <a href="{% url 'journal:journal_list' %}" class="nav-link" style="color: lime;">
                        <i class="fa-regular fa-folder-open fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Arxiv{% endblocktrans %}</span>
                    </a>
                </li>
                <li class="hover-panel">
                    <a href="{% url 'journal:about_journal' %}" class="nav-link" style="color: lime;">
                        <i class="fa-solid fa-circle-info fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Jurnal haqida{% endblocktrans %}</span>
                    </a>
                </li>
                <li class="hover-panel">
                    <a href="{% url 'journal:booking_article' %}" class="nav-link" style="color: lime;">
                        <i class="fa-regular fa-pen-to-square fs-4"></i>
                        <span class="span-color-always">{% blocktrans %}Maqola yuborish{% endblocktrans %}</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="px-3 py-2 border-bottom mb-3">
    <div class="mx-5 d-flex flex-wrap justify-content-center ">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search">
            <input type="search" class="form-control" placeholder="Qidiruv..." aria-label="Search">
        </form>
        {% if request.user.is_authenticated %}
        {% include 'components/.profile.html' %}
        {% else %}
        <div class="text-end">
            <a href="{% url 'users:login' %}" class="btn btn-light text-dark me-2">
                {% blocktrans %}Login{% endblocktrans %}
            </a>
            <a href="{% url 'users:register' %}" class="btn btn-success" style="color: lime;">
                {% blocktrans %}Sign-up{% endblocktrans %}
            </a>
        </div>
        {% endif %}
    </div>
</div>

templates/components/.header__.html
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-warning">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-5">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">{% blocktrans %}Asosiy{% endblocktrans %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">{% blocktrans %}Maqolalar{% endblocktrans %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">{% blocktrans %}Yangiliklar{% endblocktrans %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">{% blocktrans %}Jurnal haqida{% endblocktrans %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">{% blocktrans %}So'ngi sonlar{% endblocktrans %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">{% blocktrans %}Arxiv{% endblocktrans %}</a>
                </li>

            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">{% blocktrans %}Qidiruv{% endblocktrans %}</button>
            </form>
        </div>
    </div>
</nav>

templates/components/.messages.html
{% load static %}
{% load i18n %}
<div class="container col-xxl-12 my-2">
    {% if messages %}
    <ul class="list-group">
        {% for message in messages %}
        <li
        {% if message.tags %} class="list-group-item shadow list-group-item-{{ message.tags }} fw-bolder fs-5 text-center"{% endif %}>
        {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

templates/components/.profile.html
{% load static %}
{% load i18n %}
<ul class="nav col-12 col-lg-auto justify-content-center
my-md-0 text-small font-ink-free bg-dark rounded-5 hover-panel">
    <li class="">

        <a href="{% url 'users:profile' %}" class="nav-link" style="color: red;">
            {% if not request.profile.photo %}
                <i class="fa-solid fa-user fs-3"></i>
            {% else %}
                <img class="rounded rounded-circle" style="width: 2.5rem; height: 2.5rem;"
                     src="{{ request.user.profile.photo.url }}" alt="{{ request.user.username }}">
            {% endif %}
            <span class="ms-2 fs-5 fw-bold span-color-always3">

                {{ request.user.first_name|default:request.user.username }}
            </span>
        </a>
    </li>
</ul>